/**
 * Urixoft CMS Package — project integration helper.
 * Generated by `urx-cms install`. Safe to customize.
 */
export const BLOG_IMAGE_PLACEHOLDER = '/images/blog/placeholder.svg';

export const urxCmsConfig = {
	adminPath: '/cms',
	defaultTheme: 'dark' as const,
	fallbackImage: BLOG_IMAGE_PLACEHOLDER,
	/** Linode Object Storage folder prefix for uploaded blog images */
	uploadPrefix: 'urx-cms',
	/** Nav/footer label for public index route — overridden by URX_CMS_NAV_LABEL */
	navLabel: 'Blog' as const
};

export function getCmsPaths(adminPath: string = urxCmsConfig.adminPath) {
	return {
		root: adminPath,
		login: `${adminPath}/login`,
		logout: `${adminPath}/logout`,
		posts: `${adminPath}/posts`,
		newPost: `${adminPath}/posts/new`,
		editPost: (id: number | string) => `${adminPath}/posts/${id}`
	} as const;
}

export const cmsPaths = getCmsPaths();

export const cmsNavItems = [
	{ label: 'Dashboard', href: cmsPaths.root, match: (path: string) => path === cmsPaths.root },
	{
		label: 'Posts',
		href: cmsPaths.posts,
		match: (path: string) =>
			path === cmsPaths.posts ||
			(path.startsWith(`${cmsPaths.posts}/`) && path !== cmsPaths.newPost)
	},
	{ label: 'New Post', href: cmsPaths.newPost, match: (path: string) => path === cmsPaths.newPost }
] as const;

/** Normalize blog image URLs; empty values use the local placeholder. */
export function resolveBlogImageUrl(
	src?: string | null,
	fallbackImage: string = BLOG_IMAGE_PLACEHOLDER
): string {
	const trimmed = src?.trim();
	if (!trimmed || trimmed === fallbackImage) {
		return fallbackImage;
	}
	return trimmed;
}

export function isBlogImagePlaceholder(
	src?: string | null,
	fallbackImage: string = BLOG_IMAGE_PLACEHOLDER
): boolean {
	return resolveBlogImageUrl(src, fallbackImage) === fallbackImage;
}
