/**
 * Urixoft Blog Package — project integration helper.
 * Generated by `urx-blog install`. Safe to customize.
 */
import { DEFAULT_BLOG_IMAGE_PLACEHOLDER } from '@urixoft/urx-blog-package';

export const BLOG_IMAGE_PLACEHOLDER = DEFAULT_BLOG_IMAGE_PLACEHOLDER;

export const urxBlogConfig = {
	adminPath: '/blog-admin',
	fallbackImage: BLOG_IMAGE_PLACEHOLDER,
	/** Linode Object Storage folder prefix for uploaded blog images */
	uploadPrefix: 'urx-blog'
};

export { resolveBlogImageUrl, isBlogImagePlaceholder } from '@urixoft/urx-blog-package';
