/**
 * Urixoft Blog Package — project integration helper.
 * Generated by `urx-blog install`. Safe to customize.
 */
export const urxBlogConfig = {
	adminPath: '/blog-admin',
	fallbackImage: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1da?w=800&q=80'
};
