/**
 * Urixoft CMS Package — project integration helper.
 * Generated by `urx-cms install`. Safe to customize.
 */
import { PUBLIC_MANAGED_IMAGE_BASE } from '$env/static/public';

export const BLOG_IMAGE_PLACEHOLDER = '/images/blog/placeholder.svg';
export const PUBLIC_BLOG_MEDIA_PATH = '/api/blog-media';

const managedImageBase = (PUBLIC_MANAGED_IMAGE_BASE ?? '').replace(/\/$/, '');

export const urxCmsConfig = {
	adminPath: '/cms',
	defaultTheme: 'dark' as const,
	fallbackImage: BLOG_IMAGE_PLACEHOLDER,
	/** Linode Object Storage folder prefix for uploaded blog images */
	uploadPrefix: 'urx-cms',
	/** Nav/footer label for public index route — overridden by URX_CMS_NAV_LABEL */
	navLabel: 'Blog' as const
};

export function getCmsPaths(adminPath: string = urxCmsConfig.adminPath) {
	return {
		root: adminPath,
		login: `${adminPath}/login`,
		logout: `${adminPath}/logout`,
		posts: `${adminPath}/posts`,
		categories: `${adminPath}/categories`,
		activity: `${adminPath}/activity`,
		newPost: `${adminPath}/posts/new`,
		editPost: (id: number | string) => `${adminPath}/posts/${id}`,
		apiCategories: `${adminPath}/api/categories`,
		apiMedia: `${adminPath}/api/media`
	} as const;
}

export const cmsPaths = getCmsPaths();

export const cmsNavItems = [
	{ label: 'Dashboard', href: cmsPaths.root, match: (path: string) => path === cmsPaths.root },
	{
		label: 'Posts',
		href: cmsPaths.posts,
		match: (path: string) =>
			path === cmsPaths.posts ||
			(path.startsWith(`${cmsPaths.posts}/`) && path !== cmsPaths.newPost)
	},
	{ label: 'New Post', href: cmsPaths.newPost, match: (path: string) => path === cmsPaths.newPost },
	{
		label: 'Categories',
		href: cmsPaths.categories,
		match: (path: string) => path === cmsPaths.categories
	},
	{
		label: 'Activity',
		href: cmsPaths.activity,
		match: (path: string) => path === cmsPaths.activity
	}
] as const;

/** Normalize blog image URLs; empty values use the local placeholder. */
export function resolveBlogImageUrl(
	src?: string | null,
	fallbackImage: string = BLOG_IMAGE_PLACEHOLDER
): string {
	const trimmed = src?.trim();
	if (!trimmed || trimmed === fallbackImage) {
		return fallbackImage;
	}
	return trimmed;
}

export function isBlogImagePlaceholder(
	src?: string | null,
	fallbackImage: string = BLOG_IMAGE_PLACEHOLDER
): boolean {
	return resolveBlogImageUrl(src, fallbackImage) === fallbackImage;
}

/** Proxy Linode uploads through the CMS for private-bucket previews. */
export function getCmsMediaPreviewUrl(src: string): string {
	return `${cmsPaths.apiMedia}?url=${encodeURIComponent(src)}`;
}

/** Whether the URL points to a Linode upload managed by this CMS. */
export function isManagedBlogImageUrl(src?: string | null): boolean {
	const trimmed = src?.trim();
	if (!trimmed || !managedImageBase) return false;
	return trimmed === managedImageBase || trimmed.startsWith(`${managedImageBase}/`);
}

/** Public proxy for Linode uploads (no CMS login required). */
export function getPublicBlogImageUrl(src: string): string {
	return `${PUBLIC_BLOG_MEDIA_PATH}?url=${encodeURIComponent(src)}`;
}

/** Resolve a blog image for public pages; Linode uploads use the public proxy. */
export function resolvePublicBlogImageUrl(
	src?: string | null,
	fallbackImage: string = BLOG_IMAGE_PLACEHOLDER
): string {
	const resolved = resolveBlogImageUrl(src, fallbackImage);
	if (resolved === fallbackImage || !isManagedBlogImageUrl(resolved)) {
		return resolved;
	}
	return getPublicBlogImageUrl(resolved);
}

/** Rewrite Linode image URLs inside post HTML so public pages can load them. */
export function rewriteManagedBlogImagesInHtml(html: string): string {
	return html.replace(/\bsrc=(["'])(.*?)\1/gi, (_match, quote: string, src: string) => {
		return `src=${quote}${resolvePublicBlogImageUrl(src)}${quote}`;
	});
}
